# Generated by Django 4.0.1 on 2022-01-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_instance',
            new_name='django_filefield',
        ),
    ]
